### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by duncangeere** [evmaki/csv-to-midi#5]
Hi Evan! Looks like the website for this is down, and wasn't sure if you're aware :)

**Comment by evmaki** [comment]
Sorry about that!  Did some maintenance on my domain recently and the project must not have found its way back online. I just brought it back up. Let me know if you have further issues.

**Comment by duncangeere** [comment]
Working great now, I was just sending the link to someone! Thanks so much :) 

p.s. if you're still interested in in making sonifications, drop by http://decibels.community sometime!
